spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        # Existing routes remain unchanged
        - id: auth
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**
        - id: users
          uri: http://localhost:8084
          predicates:
            - Path=/users/**
        - id: documents
          uri: http://localhost:8082
          predicates:
            - Path=/documents/**
        - id: departments
          uri: http://localhost:8082
          predicates:
            - Path=/departments/**
        - id: categories
          uri: http://localhost:8082
          predicates:
            - Path=/categories/**
        - id: storage-service
          uri: http://localhost:8083
          predicates:
            - Path=/files/**
      # Add global CORS configuration
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
server:
  port: 8080
